sudo: required
language: generic
serivices:
  - docker


before_install:
  - docker build -t ssedaghati/react-test -f ./client/Dockerfile.dev ./client


scripts: 
  - docker run -e CI=true ssedaghati/react-test npm test


after_success:
  - docker build -t ssedaghati/multi-client ./client
  - docker build -t ssedaghati/multi-nginx ./nginx
  - docker build -t ssedaghati/multi-server ./server
  - docker build -t ssedaghati/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ssedaghati/multi-client
  - docker push ssedaghati/multi-nginx
  - docker push ssedaghati/multi-server
  - docker push ssedaghati/multi-worker