sudo: required
language: generic
serivices:
  - docker


before_install:
  - docker build -t ssedaghati/react-test -f ./client/Dockerfile.dev ./client


scripts: 
  - docker run -e CI=true ssedaghati/react-test npm test


after_success:
  - docker build -t ssedaghati/multi-client ./client
  - docker build -t ssedaghati/multi-nginx ./nginx
  - docker build -t ssedaghati/multi-server ./server
  - docker build -t ssedaghati/multi-worker ./worker